import type { RngMetadata } from '../../types/rng.types';
import { formatBytes, formatTimestamp } from '../../types/rng.types';

export function RngSourcePanel({ rngData }: { rngData: RngMetadata }) {
  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    // TODO: Add toast notification
  };

  return (
    <section className="rng-panel">
      <h3 className="panel-title">📡 Randomness Source</h3>

      <div className="info-grid">
        <div className="info-row">
          <span className="info-label">Source:</span>
          <span className="info-value">Internet Computer VRF</span>
        </div>

        <div className="info-row">
          <span className="info-label">Round ID:</span>
          <span className="info-value">{rngData.round_id.toString()}</span>
        </div>

        <div className="info-row">
          <span className="info-label">Timestamp:</span>
          <span className="info-value">
            {formatTimestamp(rngData.timestamp_ns)}
          </span>
        </div>

        <div className="info-block">
          <div className="info-label">Random Bytes (32 bytes):</div>
          <div className="code-block">
            {formatBytes(rngData.raw_random_bytes)}
          </div>
          <button
            onClick={() => handleCopy(formatBytes(rngData.raw_random_bytes))}
            className="copy-button"
          >
            📋 Copy
          </button>
          <div className="info-hint">
            These bytes were generated by the Internet Computer's verifiable
            random function (VRF) and cannot be predicted or manipulated.
            This is the same cryptographic randomness used by the IC blockchain
            itself - impossible to cheat or predict.
          </div>
        </div>

        <div className="info-block">
          <div className="info-label">Deck Hash (SHA-256):</div>
          <div className="code-block hash">
            {rngData.deck_hash}
          </div>
          <button
            onClick={() => handleCopy(rngData.deck_hash)}
            className="copy-button"
          >
            📋 Copy
          </button>
          <div className="info-hint">
            This hash uniquely identifies the shuffled deck. This hash was
            calculated and stored BEFORE any cards were dealt, making it
            impossible to change cards after the fact. Any modification to the
            deck would produce a completely different hash.
          </div>
        </div>
      </div>
    </section>
  );
}

