import { useState } from "react";
import type { RngMetadata } from "../../types/rng.types";
import { formatBytes, formatTimestamp } from "../../types/rng.types";

export function RngSourcePanel({ rngData }: { rngData: RngMetadata }) {
  const [copiedBytes, setCopiedBytes] = useState(false);
  const [copiedHash, setCopiedHash] = useState(false);

  const handleCopyBytes = async () => {
    await navigator.clipboard.writeText(formatBytes(rngData.raw_random_bytes));
    setCopiedBytes(true);
    setTimeout(() => setCopiedBytes(false), 2000);
  };

  const handleCopyHash = async () => {
    await navigator.clipboard.writeText(rngData.deck_hash);
    setCopiedHash(true);
    setTimeout(() => setCopiedHash(false), 2000);
  };

  return (
    <section className="rng-panel">
      <h3 className="panel-title">📡 Randomness Source</h3>

      <div className="info-grid">
        <div className="info-row">
          <span className="info-label">Source:</span>
          <span className="info-value">Internet Computer VRF</span>
        </div>

        <div className="info-row">
          <span className="info-label">Round ID:</span>
          <span className="info-value">{rngData.round_id.toString()}</span>
        </div>

        {/* 🔒 SECURITY: Only show timestamp after game ends */}
        {rngData.timestamp_ns !== BigInt(0) && (
          <div className="info-row">
            <span className="info-label">Timestamp:</span>
            <span className="info-value">
              {formatTimestamp(rngData.timestamp_ns)}
            </span>
          </div>
        )}

        <div className="info-block">
          <div className="info-label">Random Bytes (32 bytes):</div>
          <div className="code-block">
            {formatBytes(rngData.raw_random_bytes)}
            <button
              onClick={handleCopyBytes}
              className={`copy-button-inline ${copiedBytes ? "copied" : ""}`}
              title="Copy to clipboard"
            >
              {copiedBytes ? "✓" : "📋"}
            </button>
          </div>
          <div className="info-hint">
            These bytes were generated by the Internet Computer's verifiable
            random function (VRF) and cannot be predicted or manipulated. This
            is the same cryptographic randomness used by the IC blockchain
            itself - impossible to cheat or predict.
          </div>
        </div>

        <div className="info-block">
          <div className="info-label">Deck Hash (SHA-256):</div>
          <div className="code-block hash">
            {rngData.deck_hash}
            <button
              onClick={handleCopyHash}
              className={`copy-button-inline ${copiedHash ? "copied" : ""}`}
              title="Copy to clipboard"
            >
              {copiedHash ? "✓" : "📋"}
            </button>
          </div>
          <div className="info-hint">
            This hash uniquely identifies the shuffled deck. This hash was
            calculated and stored BEFORE any cards were dealt, making it
            impossible to change cards after the fact. Any modification to the
            deck would produce a completely different hash.
          </div>
        </div>
      </div>
    </section>
  );
}
