import classNames from 'classnames';
import { memo, useMemo } from 'react';

import { useCopyToClipboard } from '@/src/hooks/clipboard';
import { ButtonComponent, List, ListItem } from '@zk-game-dao/ui';

import type { RngMetadata } from '../../types/rng.types';
import { formatBytes, formatTimestamp } from '../../types/rng.types';

export const RngSourcePanelComponent = memo<{ rngData: RngMetadata }>(({ rngData }) => {
  const randomBytesText = useMemo(
    () => formatBytes(rngData.raw_random_bytes),
    [rngData.raw_random_bytes]
  );
  const copyBytes = useCopyToClipboard(randomBytesText);
  const copyHash = useCopyToClipboard(rngData.deck_hash);

  return (
    <div className="material rounded-xl p-6 mb-5 bg-transparent space-y-6 transition-all">
      <h3 className="type-top mb-2 flex items-center gap-2 text-blue-200/90 font-semibold tracking-wide drop-shadow-sm">
        Randomness Source
      </h3>

      <div>
        <List variant={{ type: 'default', readonly: true }}>
          <ListItem rightLabel="Internet Computer VRF">Source</ListItem>
          <ListItem rightLabel={<span className="font-mono">{rngData.round_id.toString()}</span>}>
            Round ID
          </ListItem>
          {rngData.timestamp_ns !== BigInt(0) && (
            <ListItem rightLabel={formatTimestamp(rngData.timestamp_ns)}>
              Timestamp
            </ListItem>
          )}
        </List>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-1">
        {/* Random Bytes */}
        <div className="flex flex-col gap-2 group pl-4 pb-1 bg-transparent rounded-lg transition-all">
          <div className="flex items-center justify-between mb-1">
            <span className="type-subheadline font-medium text-green-200/90">Random Bytes (32 bytes)</span>
            <ButtonComponent onClick={copyBytes} variant="naked">
              <span role="img" aria-label="copy">📋</span> Copy
            </ButtonComponent>
          </div>
          <div className="material rounded p-3 text-green-100 font-mono text-xs break-all backdrop-blur-sm overflow-x-auto select-all transition-all">
            <span data-testid="random-bytes">{randomBytesText}</span>
          </div>
          <p className="type-tiny mt-1 opacity-80 text-green-100/80 leading-relaxed">
            Generated by the Internet Computer’s secure VRF. Impossible to predict or manipulate.
          </p>
        </div>
        {/* Deck Hash */}
        <div className="flex flex-col gap-2 group pl-4 pb-1 bg-transparent rounded-lg transition-all">
          <div className="flex items-center justify-between mb-1">
            <span className="type-subheadline font-medium text-blue-200/90">Deck Hash (SHA-256)</span>
            <ButtonComponent onClick={copyHash} variant="naked">
              <span role="img" aria-label="copy">📋</span> Copy
            </ButtonComponent>
          </div>
          <div className="material rounded p-3 text-blue-100 font-mono text-xs break-all overflow-x-auto select-all backdrop-blur-sm transition-all">
            <span data-testid="deck-hash">{rngData.deck_hash}</span>
          </div>
          <p className="type-tiny mt-1 opacity-80 text-blue-100/80 leading-relaxed">
            Uniquely identifies the shuffled deck before the round. Any change would alter this hash — cryptographic proof of fairness.
          </p>
        </div>
      </div>
    </div>
  );
});
RngSourcePanelComponent.displayName = 'RngSourcePanelComponent';
